FROM conanio/clang8:latest

RUN sudo apt-get -qq update \
    && sudo apt-get install -y --no-install-recommends \
    libglu1-mesa-dev \
    mesa-common-dev \
    libxmu-dev \
    libxi-dev \
    qt5-default \
    jq \
    python2.7 \
    zip \
    && sudo rm -rf /var/lib/apt/lists/*
