// Copyright (c) 2020 The Orbit Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LINUX_TRACING_PERF_EVENT_H_
#define LINUX_TRACING_PERF_EVENT_H_

#include <asm/perf_regs.h>
#include <string.h>
#include <sys/types.h>

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <variant>
#include <vector>

#include "GrpcProtos/Constants.h"
#include "OrbitBase/MakeUniqueForOverwrite.h"
#include "PerfEventRecords.h"

namespace orbit_linux_tracing {

class PerfEventVisitor;

static constexpr int kNotOrderedInAnyFileDescriptor = -1;

std::array<uint64_t, PERF_REG_X86_64_MAX> perf_event_sample_regs_user_all_to_register_array(
    const perf_event_sample_regs_user_all& regs);

struct ForkPerfEvent {
  pid_t pid;
  pid_t tid;
};

struct ExitPerfEvent {
  pid_t pid;
  pid_t tid;
};

struct LostPerfEvent {
  uint64_t previous_timestamp = 0;
};

// This class doesn't correspond to any event generated by perf_event_open. Rather, these events are
// produced by PerfEventProcessor. We need them to be part of the same PerfEvent hierarchy.
struct DiscardedPerfEvent {
  uint64_t begin_timestamp_ns;
};

struct StackSamplePerfEvent {
  [[nodiscard]] std::array<uint64_t, PERF_REG_X86_64_MAX> GetRegisters() const {
    return perf_event_sample_regs_user_all_to_register_array(*regs);
  }
  [[nodiscard]] const char* GetStackData() const { return data.get(); }
  // Handing out this non const pointer makes the stack data mutable even if the
  // StackSamplePerfEvent is const.  This mutablility is needed in
  // UprobesReturnAddressManager::PatchSample.
  [[nodiscard]] char* GetMutableStackData() const { return data.get(); }
  [[nodiscard]] uint64_t GetStackSize() const { return dyn_size; }

  pid_t pid;
  pid_t tid;
  std::unique_ptr<perf_event_sample_regs_user_all> regs;
  uint64_t dyn_size;
  std::unique_ptr<char[]> data;
};

struct CallchainSamplePerfEvent {
  [[nodiscard]] const uint64_t* GetCallchain() const { return ips.get(); }
  [[nodiscard]] uint64_t GetCallchainSize() const { return ips_size; }
  [[nodiscard]] std::array<uint64_t, PERF_REG_X86_64_MAX> GetRegisters() const {
    return perf_event_sample_regs_user_all_to_register_array(*regs);
  }
  [[nodiscard]] const char* GetStackData() const { return data.get(); }
  void SetIps(const std::vector<uint64_t>& new_ips) const {
    ips_size = new_ips.size();
    ips = make_unique_for_overwrite<uint64_t[]>(ips_size);
    memcpy(ips.get(), new_ips.data(), ips_size * sizeof(uint64_t));
  }
  [[nodiscard]] std::vector<uint64_t> CopyOfIpsAsVector() const {
    return std::vector<uint64_t>(ips.get(), ips.get() + ips_size);
  }

  pid_t pid;
  pid_t tid;
  // Mutability is needed in SetIps which in turn is needed by
  // LeafFunctionCallManager::PatchCallerOfLeafFunction.
  mutable uint64_t ips_size;
  mutable std::unique_ptr<uint64_t[]> ips;
  std::unique_ptr<perf_event_sample_regs_user_all> regs;
  std::unique_ptr<char[]> data;
};

struct UprobesPerfEvent {
  pid_t pid;
  pid_t tid;
  uint32_t cpu;
  uint64_t function_id = orbit_grpc_protos::kInvalidFunctionId;
  uint64_t sp;
  uint64_t ip;
  uint64_t return_address;
};

struct UprobesWithArgumentsPerfEvent {
  pid_t pid;
  pid_t tid;
  uint32_t cpu;
  uint64_t function_id = orbit_grpc_protos::kInvalidFunctionId;
  uint64_t return_address;
  perf_event_sample_regs_user_sp_ip_arguments regs;
};

struct UretprobesPerfEvent {
  pid_t pid;
  pid_t tid;
};

struct UretprobesWithReturnValuePerfEvent {
  pid_t pid;
  pid_t tid;
  uint64_t rax;
};

struct MmapPerfEvent {
  uint64_t address;
  uint64_t length;
  uint64_t page_offset;
  std::string filename;
  pid_t pid;
};

struct GenericTracepointPerfEvent {
  pid_t pid;
  pid_t tid;
  uint32_t cpu;
  uint32_t size;
};

struct TaskNewtaskPerfEvent {
  char comm[16];
  pid_t new_tid;
};

struct TaskRenamePerfEvent {
  char newcomm[16];
  pid_t renamed_tid;
};

struct SchedSwitchPerfEvent {
  uint32_t cpu;
  pid_t prev_pid_or_minus_one;
  pid_t prev_tid;
  int64_t prev_state;
  int32_t next_tid;
};

struct SchedWakeupPerfEvent {
  pid_t woken_tid;
};

struct AmdgpuCsIoctlPerfEvent {
  pid_t pid;
  pid_t tid;
  uint32_t context;
  uint32_t seqno;
  std::string timeline_string;
};

struct AmdgpuSchedRunJobPerfEvent {
  pid_t pid;
  pid_t tid;
  uint32_t context;
  uint32_t seqno;
  std::string timeline_string;
};

struct DmaFenceSignaledPerfEvent {
  pid_t pid;
  pid_t tid;
  uint32_t context;
  uint32_t seqno;
  std::string timeline_string;
};

struct PerfEvent {
  // These top-level fields are common to all events, while each of the `...PerfEvent`s in the
  // `data` variant contains the data specific to each type of event.
  uint64_t timestamp;
  int ordered_in_file_descriptor = kNotOrderedInAnyFileDescriptor;
  std::variant<ForkPerfEvent, ExitPerfEvent, LostPerfEvent, DiscardedPerfEvent,
               StackSamplePerfEvent, CallchainSamplePerfEvent, UprobesPerfEvent,
               UprobesWithArgumentsPerfEvent, UretprobesPerfEvent,
               UretprobesWithReturnValuePerfEvent, MmapPerfEvent, GenericTracepointPerfEvent,
               TaskNewtaskPerfEvent, TaskRenamePerfEvent, SchedSwitchPerfEvent,
               SchedWakeupPerfEvent, AmdgpuCsIoctlPerfEvent, AmdgpuSchedRunJobPerfEvent,
               DmaFenceSignaledPerfEvent>
      data;

  void Accept(PerfEventVisitor* visitor) const;
};

}  // namespace orbit_linux_tracing

#endif  // LINUX_TRACING_PERF_EVENT_H_
